Bringing the UC2 controllers and widgets to the main branch
ImSwitch/ImSwitch pull request #186
Opened 2023-09-25 08:21 UTC by beniroquai

This is a huge pull request and I honestly don't know how to deal with it. Perhaps we have a session to work on it? @jacopoabramo ?

2023-09-25 08:22 UTC, beniroquai commented
I think the first task would be to resolve the test-cases I guess? ;)

2023-09-25 20:37 UTC, beniroquai commented
@jacopoabramo I have adapted the tests slightly. The test_scan is broken it seems..

2023-09-26 06:11 UTC, beniroquai commented
@jacopoabramo help :D 
https://github.com/openUC2/ImSwitch/actions/runs/6304767094/job/17127008001#step:6:159

All tests completed, but a cryptic error. Any ideas why?

2023-09-26 07:09 UTC, jacopoabramo commented
Checking the macos-latest unit test report:

>       self._esp32 = uc2.UC2Client(host=self._host, port=80, identity=self._identity, serialport=self._serialport, baudrate=115200, logger=self.__logger)
E       TypeError: __init__() got an unexpected keyword argument 'logger'

This seems to be the first reason that the unit test fails; I'm pretty sure new errors will pop up slowly but surely

2023-09-26 07:12 UTC, beniroquai commented
This issue has been resolved already. So there is a new error saying:

```
imswitch/imcontrol/_test/unit/test_recording.py: 197 warnings
  /Users/runner/work/ImSwitch/ImSwitch/imswitch/imcontrol/model/managers/RecordingManager.py:537: DeprecationWarning: an integer is required (got type numpy.float64).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
    self.__recordingManager.sigRecordingTimeUpdated.emit(

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
================= 20 passed, 218 warnings in 84.28s (0:01:24) ==================
Error: Process completed with exit code 139.
```

2023-09-26 07:13 UTC, jacopoabramo commented
Interesting, it seems that the runner crashes but I could not for the life of me understand why this happens. I'll try to check what that error code means

2023-10-14 10:13 UTC, jacopoabramo commented
@beniroquai please replace all the calls to `print` with logger calls. You can create a local reference to the central logger instance with the `initLogger` function in `imswitch.imcommon.model`

2023-10-14 10:37 UTC, jacopoabramo commented
I tested the changes locally and run the unit test; they seem to pass. It would be great though if you could add some unit test of your own to increase coverage, @beniroquai

2023-10-17 07:26 UTC, beniroquai commented
Thanks for commenting! I cleaned up some unused controllers and replaced prints with logs. 
I had one question. In my last commit [4448ace](https://github.com/ImSwitch/ImSwitch/pull/186/commits/4448acebedf96615e741c1edbd625d9792ce8481) I reverted a change which overwrote the `tryInherit`-stuff. My impression was that this slows down ImSwitch's startup. Any comments on that?

2023-10-17 07:30 UTC, jacopoabramo commented
The initLogger function tries to inherit from a parent of the object that is creating the logger instance, so to log referring to the parent and not the current object.

From the function:

```py
    logger = None

    if tryInheritParent:
        # Use logger from first parent in stack that has one
        for frameInfo in inspect.stack():
            frameLocals = frameInfo[0].f_locals
            if 'self' not in frameLocals:
                continue

            parent = frameLocals['self']
            parentRef = weakref.ref(parent)
            if parentRef not in objLoggers:
                continue

            logger = objLoggers[parentRef]
            break
```

If there's a deep stack of objects it may take a while.

2023-10-17 12:15 UTC, jacopoabramo commented
@beniroquai can you run the the failing test locally to see what's the output?

2023-10-17 17:03 UTC, beniroquai commented
On my mac I get this:

```bash
(imswitch) (base) MacBook-Pro-9:ImSwitch bene$ python -m pytest --pyargs imswitch -v --ignore=imswitch/imcontrol/_test/ui/test_example_setups.py
/Users/bene/opt/anaconda3/envs/imswitch/lib/python3.9/site-packages/paramiko/transport.py:219: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,
================================================================ test session starts =================================================================
platform darwin -- Python 3.9.15, pytest-7.2.1, pluggy-1.0.0 -- /Users/bene/opt/anaconda3/envs/imswitch/bin/python
cachedir: .pytest_cache
PyQt5 5.15.9 -- Qt runtime 5.15.2 -- Qt compiled 5.15.2
rootdir: /Users/bene/Dropbox/Dokumente/Promotion/PROJECTS/MicronController/PYTHON/ImSwitch
plugins: qt-4.2.0, napari-plugin-engine-0.2.0, anyio-3.7.1, npe2-0.7.2, napari-0.4.18
collected 20 items                                                                                                                                   

imswitch/imcontrol/_test/ui/test_liveview.py::test_liveview_no_error httpd started on port 5001
INFO:     Started server process [56111]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
PASSED                                                                    [  5%]
imswitch/imcontrol/_test/ui/test_liveview.py::test_grid_no_error PASSED                                                                        [ 10%]
imswitch/imcontrol/_test/ui/test_liveview.py::test_crosshair_no_error PASSED                                                                   [ 15%]
imswitch/imcontrol/_test/ui/test_liveview.py::test_close_no_error PASSED                                                                       [ 20%]
imswitch/imcontrol/_test/ui/test_without_widgets.py::test_without_widgets_starts_no_error httpd failed to start on port 5001
[Errno 48] Address already in use
INFO:     Started server process [56111]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
ERROR:    [Errno 48] error while attempting to bind on address ('0.0.0.0', 8000): address already in use
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
PASSED                                               [ 25%]
imswitch/imcontrol/_test/ui/test_without_widgets.py::test_without_widgets_close_no_error PASSED                                                [ 30%]
imswitch/imcontrol/_test/unit/test_acquisition.py::test_acquisition_liveview_single[detectorInfos0] PASSED                                     [ 35%]
imswitch/imcontrol/_test/unit/test_acquisition.py::test_acquisition_liveview_single[detectorInfos1] PASSED                                     [ 40%]
imswitch/imcontrol/_test/unit/test_acquisition.py::test_acquisition_liveview_multi[Camera 1] PASSED                                            [ 45%]
imswitch/imcontrol/_test/unit/test_acquisition.py::test_acquisition_liveview_multi[Camera 2] PASSED                                            [ 50%]
imswitch/imcontrol/_test/unit/test_recording.py::test_recording_spec_frames[detectorInfos0-10] PASSED                                          [ 55%]
imswitch/imcontrol/_test/unit/test_recording.py::test_recording_spec_frames[detectorInfos1-53] PASSED                                          [ 60%]
imswitch/imcontrol/_test/unit/test_recording.py::test_recording_spec_time[detectorInfos0] PASSED                                               [ 65%]
imswitch/imcontrol/_test/unit/test_recording.py::test_recording_spec_time[detectorInfos1] PASSED                                               [ 70%]
imswitch/imcontrol/_test/unit/test_recording.py::test_recording_spec_time[detectorInfos2] PASSED                                               [ 75%]
imswitch/imcontrol/_test/unit/test_scan.py::test_scan_signals PASSED                                                                           [ 80%]
imswitch/imcontrol/_test/unit/test_stores.py::test_storer_instatiation PASSED                                                                  [ 85%]
imswitch/imcontrol/_test/unit/test_stores.py::test_zarr_storer PASSED                                                                          [ 90%]
imswitch/imcontrol/_test/unit/test_stores.py::test_tiff_storer PASSED                                                                          [ 95%]
imswitch/imcontrol/_test/unit/test_stores.py::test_hdf5_storer PASSED                                                                          [100%]

================================================================== warnings summary ==================================================================
../../../../../../../opt/anaconda3/envs/imswitch/lib/python3.9/site-packages/google_crc32c/__config__.py:18
  /Users/bene/opt/anaconda3/envs/imswitch/lib/python3.9/site-packages/google_crc32c/__config__.py:18: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
    import pkg_resources

../../../../../../../opt/anaconda3/envs/imswitch/lib/python3.9/site-packages/pkg_resources/__init__.py:2871
../../../../../../../opt/anaconda3/envs/imswitch/lib/python3.9/site-packages/pkg_resources/__init__.py:2871
../../../../../../../opt/anaconda3/envs/imswitch/lib/python3.9/site-packages/pkg_resources/__init__.py:2871
../../../../../../../opt/anaconda3/envs/imswitch/lib/python3.9/site-packages/pkg_resources/__init__.py:2871
../../../../../../../opt/anaconda3/envs/imswitch/lib/python3.9/site-packages/pkg_resources/__init__.py:2871
../../../../../../../opt/anaconda3/envs/imswitch/lib/python3.9/site-packages/pkg_resources/__init__.py:2871
../../../../../../../opt/anaconda3/envs/imswitch/lib/python3.9/site-packages/pkg_resources/__init__.py:2871
  /Users/bene/opt/anaconda3/envs/imswitch/lib/python3.9/site-packages/pkg_resources/__init__.py:2871: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
  Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
    declare_namespace(pkg)

../../../../../../../opt/anaconda3/envs/imswitch/lib/python3.9/site-packages/pkg_resources/__init__.py:2871
../../../../../../../opt/anaconda3/envs/imswitch/lib/python3.9/site-packages/pkg_resources/__init__.py:2871
../../../../../../../opt/anaconda3/envs/imswitch/lib/python3.9/site-packages/pkg_resources/__init__.py:2871
  /Users/bene/opt/anaconda3/envs/imswitch/lib/python3.9/site-packages/pkg_resources/__init__.py:2871: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google.cloud')`.
  Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
    declare_namespace(pkg)

../../../../../../../opt/anaconda3/envs/imswitch/lib/python3.9/site-packages/pkg_resources/__init__.py:2350
../../../../../../../opt/anaconda3/envs/imswitch/lib/python3.9/site-packages/pkg_resources/__init__.py:2350
  /Users/bene/opt/anaconda3/envs/imswitch/lib/python3.9/site-packages/pkg_resources/__init__.py:2350: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
  Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
    declare_namespace(parent)

../../../../../../../opt/anaconda3/envs/imswitch/lib/python3.9/site-packages/pkg_resources/__init__.py:2871
  /Users/bene/opt/anaconda3/envs/imswitch/lib/python3.9/site-packages/pkg_resources/__init__.py:2871: DeprecationWarning: Deprecated call to `pkg_resources [...]

2023-10-17 17:10 UTC, jacopoabramo commented
Well, that's funky. Were you importing one of those packages before? If so where? I'll take a look and review it (it's easier to ask you since the PR is massive).

As for test cases, would be nice to have a mock configuration of a standard UC2 setup and try to imitate the examples in the `_test/unit` folder.

2023-10-17 17:13 UTC, jacopoabramo commented
```
imswitch/imcontrol/_test/ui/test_without_widgets.py::test_without_widgets_starts_no_error httpd failed to start on port 5001
[Errno 48] Address already in use
INFO:     Started server process [56111]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
ERROR:    [Errno 48] error while attempting to bind on address ('0.0.0.0', 8000): address already in use
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
PASSED  
```

Could be nice if a local server to attach ImSwitch to in the unit tests could be added as well... Like a mock server or something

2023-10-17 18:10 UTC, jacopoabramo commented
@beniroquai I think you should probably update this branch with the changes from the master branch. In order:

- merge from ImSwitch:master to ImSwitch:uc2
- merge from ImSwitch:uc2 to openUC2:master

Hopefully we should sync up.

2023-10-19 08:24 UTC, beniroquai commented
@jacopoabramo, we should definitely think about a versioning system. E.g. CLI when uploading to pypi.

2023-10-19 08:24 UTC, beniroquai commented
What is your favorite way to automate this?

2023-10-19 08:28 UTC, jacopoabramo commented
I'm not experienced enough to setup a workflow for automatically packaging to PyPi when a new version is released but [here](https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/) they seem to describe the process. If you have a preferred way I'm all hears, this is new stuff to me

2023-10-19 08:36 UTC, beniroquai commented
It has already been established, but replacing the version number is missing. So either we do a PR on new version and replace the __version__ string with the version TAG or we use this as the version TAG . the workflow is inside github actions. the uc2 branch works

2023-10-19 08:38 UTC, jacopoabramo commented
I'm sorry, I got lost. Could you clarify this for me?

2023-10-19 08:53 UTC, beniroquai commented
First thing: I merged the imswitch/master into imswitch/uc2. Did that help? ;) 
However, the PR I filed is trying to merge openuc2/master into imswitch/uc2..so what's next?

The workflow is here:https://github.com/openUC2/ImSwitch/blob/master/.github/workflows/imswitch-pypi.yml#L30 with replacement of the version-number

2023-10-19 08:58 UTC, jacopoabramo commented
> The workflow is here:https://github.com/openUC2/ImSwitch/blob/master/.github/workflows/imswitch-pypi.yml#L30 with replacement of the version-number

Ohh nice, this is perfect. And this is part of the PR?

> However, the PR I filed is trying to merge openuc2/master into imswitch/uc2..so what's next?

I checked and now since your `ImSwitch:uc2` branch is up to date with the master, it should be fine. I don't know why I was thinking otherwise... now we just need to fix these failing test

2023-10-19 09:06 UTC, jacopoabramo requested changes

2023-10-20 07:32 UTC, beniroquai commented
@jacopoabramo, quick question. Are these changes based on the Imswitch/UC2 or the openUC2/master branch? I guess some of the changes I already made .. but in the openUC2 repo

2023-10-20 11:28 UTC, jacopoabramo commented
@beniroquai some of the changes were already existing in the master repo, exactly. If they are already there you can just mark them as done.

2023-10-30 19:04 UTC, beniroquai commented on imswitch/imblockly/controller/ImScrMainController.py
> +        def do_GET(self):
The current version looks as follows:

```py
    class StaticServer(BaseHTTPRequestHandler):
        def do_GET(self):
            root = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "view", "static", "index.html")
            if self.path == '/':
                filename = root + '/index.html'
            else:
                filename = root + self.path
            self.send_response(200)
            if filename[-4:] == '.css':
                self.send_header('Content-type', 'text/css')
            elif filename[-5:] == '.json':
                self.send_header('Content-type', 'application/javascript')
            elif filename[-3:] == '.js':
                self.send_header('Content-type', 'application/javascript')
            elif filename[-4:] == '.ico':
                self.send_header('Content-type', 'image/x-icon')
            else:
                self.send_header('Content-type', 'text/html')
            self.end_headers()
            with open(filename, 'rb') as fh:
                html = fh.read()
                self.wfile.write(html)
```

2023-10-30 19:06 UTC, beniroquai commented on .github/workflows/imswitch-packconda.yml
Good question. I'll remove it for now. I attempted to have imswitch built in the Conda world. But too many non-conda dependencies avoid this effort.

2023-10-30 19:07 UTC, beniroquai commented on README.md
>  ### Option C: Install from Github (UC2 version)
removed.

2023-10-30 19:10 UTC, beniroquai commented on construct.yaml
artifact to package imswitch into conda. removed

2023-11-07 16:30 UTC, beniroquai reviewed
Hey @jacopoabramo I have removed ImBlockly for now as it's too confusing. I have updated many parts of the repo according to your suggestions. What do you think?

2023-11-07 16:30 UTC, beniroquai commented on docs/changelog.rst
> +- Added features for open microscopy hardware (OpenUC2, SQUID, ESP32) more on beniroquai's fork
I removed the changelog

2023-11-07 16:30 UTC, beniroquai commented on docs/conf.py
> +copyright = '2020-2022 ImSwitch developers'
Done

2023-11-07 16:30 UTC, beniroquai commented on imswitch/_data/user_defaults/uc2_configs/pindefUC2Standalon1.json
I rather remove it.

2023-11-07 16:30 UTC, beniroquai commented on imswitch/app/public/assets/css/style.css
It was a test to control ImSwitch from Typescript. I remove it.

2023-11-07 16:30 UTC, beniroquai commented on imswitch/app/public/assets/js/index.js
nope. Removed it

2023-11-07 16:30 UTC, beniroquai commented on imswitch/imblockly/__init__.py
No, it's very experimental and breaking since the QT Webview is not really supported anymore (?)

2023-11-07 16:30 UTC, beniroquai commented on imswitch/imblockly/controller/CommunicationChannel.py
Sure, who could write this? :-P
I would rather state: "experimental" and then if there is somebody keen on playing with it, fine. This could be a `first nice plugin` ;-)

2023-11-07 16:30 UTC, beniroquai commented on imswitch/imblockly/controller/ImScrMainViewController.py
> +#from .BlockController import BlockController
Done

2023-11-07 16:30 UTC, beniroquai commented on imswitch/imblockly/controller/ImScrMainViewController.py
> +class ImScrMainViewController(ImScrWidgetController):
As said, the imblockly was experimental. Maybe I create a branch and leave it there?

2023-11-07 16:30 UTC, beniroquai commented on imswitch/imblockly/model/ScriptExecutor.py
Ok, I'll remove imblockly once and for all

2023-11-07 16:30 UTC, beniroquai commented on imswitch/imcommon/view/guitools/joystick.py
Would you mind doing that? ; )

2023-11-07 16:30 UTC, beniroquai commented on imswitch/imcontrol/__test_Manager.py
I guess this is not coming from me.

2023-11-07 16:30 UTC, beniroquai commented on imswitch/imblockly/controller/ImScrMainController.py
> +class MyServer:
It's gone now.

2023-11-07 16:30 UTC, beniroquai commented on imswitch/imcommon/model/api.py
Nope, streaming images and retreiving images via HTTP

2023-11-07 16:30 UTC, beniroquai commented on imswitch/imcontrol/_test/__init__.py
I haven't touched it - i guess ;)

2023-11-08 11:25 UTC, beniroquai commented
@jacopoabramo should I change the target branch to become dev or uc2?

2023-11-08 12:20 UTC, jacopoabramo commented
@beniroquai there are some conflicts to resolve first. I'll take a look locally

2023-11-08 12:39 UTC, merged

2023-11-08 21:22 UTC, beniroquai commented
Thanks @jacopoabramo. Let me know what I have to do know ;)

2023-11-08 21:38 UTC, jacopoabramo commented
I managed to solve some of the conflicts. You should add your updates on that PR side

2023-11-08 21:46 UTC, beniroquai commented
Aren't they automatically reflected? I see all the latest changes. So should be good to go! :)

2023-11-08 21:49 UTC, jacopoabramo commented
Oh really? Cool then